services:
  web:
    build: .
    command: sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    stdin_open: true
    tty: true
